//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almoxarifado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDAlmoxarifadoEntities2 : DbContext
    {
        public BDAlmoxarifadoEntities2()
            : base("name=BDAlmoxarifadoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Entrada> Entrada { get; set; }
        public virtual DbSet<Entradaproduto> Entradaproduto { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Saida> Saida { get; set; }
        public virtual DbSet<Saidaproduto> Saidaproduto { get; set; }
    }
}
